iep-newer/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iep_newer;
using iep_newer.Models;
using Microsoft.AspNet.Identity;

namespace iep_newer.Controllers
{
    public class AuctionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private void updateAuctionClosed(ref Auction auction)
        {
            logger.Debug("Auction updateAuctionClosed for " + auction.name);
            if (auction.closed < DateTime.Now)
            {
                if (auction.Bids.Count > 0)
                {
                    auction.state = Auction.State.SOLD;
                }
                else
                {
                    auction.state = Auction.State.EXPIRED;
                }
            }
        }

        // GET: Auction/Open
        public HttpStatusCodeResult Open(int id)
        {
            logger.Debug("Auction Open " + id);
            Auction auction = db.Auctions.Find(id);

            auction.opened = DateTime.Now;
            auction.state = Auction.State.OPEN;
            auction.closed = DateTime.Now.AddSeconds(auction.duration);

            db.SaveChanges();

            return new HttpStatusCodeResult(200);
        }

        // GET: Auction/Bid

        public DateTime Bid(int id)
        {
            logger.Debug("Auction Bid " + id);
            Bid bid = new Models.Bid();

            var user = db.Users.Find(User.Identity.GetUserId());

            if (user.Tokens == 0)
            {
                //return new HttpStatusCodeResult(400);
                return DateTime.MinValue;
            }

            Auction auction = db.Auctions.Find(id);

            updateAuctionClosed(ref auction);

            if (auction.state != Auction.State.OPEN)
            {
                //return new HttpStatusCodeResult(400);
                return DateTime.MinValue;
            }

            if (auction.closed - DateTime.Now < TimeSpan.FromSeconds(10))
            {
                auction.closed = DateTime.Now.AddSeconds(10);
            }

            bid.auction = auction;

            //auction.Bids.Add(bid);
            auction.last_bid_user = user;

            bid.user = user;

            bid.created = DateTime.Now;

            bid.auction.current_price += 1;
            bid.user.Tokens -= 1;

            db.Bids.Add(bid);
            db.SaveChanges();

            //return new HttpStatusCodeResult(200);
            return bid.created;
        }

        // GET: Auction/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            logger.Debug("Auction Create Get ");
            return View();
        }

        // POST: Auction/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "name,duration,starting_price,image_file")] Auction auction)
        {
            logger.Debug("Auction Create Post ");
            auction.created = DateTime.Now;
            logger.Debug("Auction Create Post created " + auction.created);
            auction.current_price = auction.starting_price;
            logger.Debug("Auction Create Post starting_price " + auction.starting_price);
            auction.image = new byte[auction.image_file.ContentLength];
            auction.image_file.InputStream.Read(auction.image, 0, auction.image.Length);
            auction.state = Auction.State.READY;

            if (ModelState.IsValid)
            {
                db.Auctions.Add(auction);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(auction);
        }

        // GET: Auction/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            logger.Debug("Auction Edit Get ");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }

        // POST: Auction/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "id,name,duration,starting_price,image_file")] Auction auction)
        {
            Auction auctionDB = db.Auctions.Find(auction.id);

            auctionDB.name = auction.name;
            auctionDB.duration = auction.duration;
            logger.Debug("Auction Edit Post ");
            auctionDB.created = DateTime.Now;
            logger.Debug("Auction Edit Post created " + auction.created);
            auctionDB.current_price = auctionDB.starting_price = auction.starting_price;
            logger.Debug("Auction Edit Post starting_price " + auction.starting_price);
            auctionDB.image_file = auction.image_file;
            auctionDB.image = new byte[auctionDB.image_file.ContentLength];
            auctionDB.image_file.InputStream.Read(auctionDB.image, 0, auctionDB.image.Length);
            
            if (ModelState.IsValid)
            {
                db.Entry(auctionDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(auction);
        }

        // GET: Auction/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            db.Auctions.Remove(auction);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        // GET: Auction/Details/5
        public ActionResult Details(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.UserName = db.Users.Find(User.Identity.GetUserId()).Name;
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }

            ViewBag.closed = auction.closed;

            return View(auction);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iep-newer/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iep_newer.Models;
using Microsoft.AspNet.Identity;
using System.Net.Mail;  

namespace iep_newer.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Order/New
        
        public int New()
        {
            logger.Debug("Order New");

            var order = new Order();

            var user = db.Users.Find(User.Identity.GetUserId());

            order.user = user;

            order.state = Order.OrderState.WAIT;

            order.created = DateTime.Now;

            db.Orders.Add(order);
            db.SaveChanges();

            return order.id;
        }

        //public int NewFejk()
        //{
        //    var order = new Order();

        //    var user = db.Users.First();

        //    order.user = user;

        //    order.state = Order.OrderState.FAIL;

        //    order.created = DateTime.Now;

        //    db.Orders.Add(order);
        //    db.SaveChanges();

        //    return order.id;
        //}

        const int ORDERS_PER_PAGE = 5;

        // GET: Order
        [Authorize]
        public ActionResult Index(string msg, int? pagenum)
        {
            logger.Debug("Order Index msg " + msg + " userid " + User.Identity.GetUserId());
            var thisUser = User.Identity.GetUserId();
            IEnumerable<Order> orders = db.Orders;
            orders = orders.Where(o => o.user_id == thisUser);//.Include(o => o.user);
            orders = orders.OrderByDescending(o => o.created);

            ViewBag.pages = Math.Ceiling((double)orders.Count() / ORDERS_PER_PAGE);

            orders = orders.Skip(ORDERS_PER_PAGE * (pagenum ?? default(int))).Take(ORDERS_PER_PAGE);

            ViewBag.msg = msg;
            ViewBag.pagenum = pagenum;
            return View(orders.ToList());
        }

        //// GET: Order/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Orders.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(order);
        //}

        // GET: Order/Finish

        //// GET: Order/Create
        //public ActionResult Create()
        //{
        //    //var user = db.Users.Find(User.Identity.GetUserId());
        //    //ViewBag.user_id = new SelectList(db.Users, "Id", "Name");
        //    return View();
        //}

        //// POST: Order/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,user_id,created,tokens,price")] Order order)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Orders.Add(order);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    //ViewBag.user_id = new SelectList(db.Users, "Id", "Name", order.user_id);
        //    return View(order);
        //}

        //// GET: Order/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Order order = db.Orders.Find(id);
        //    if (order == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    //ViewBag.user_id = new SelectList(db.Users, "Id", "Name", order.user_id);
        //    return View(order);
        //}

        //// POST: Order/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "id,user_id,created,tokens,price")] Order order)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(order).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    //ViewBag.user_id = new SelectList(db.Users, "Id", "Name", order.user_id);
        //    return View(order);
        //}

        // GET: Order/Delete/5
        public ActionResult Delete(int? id, int? pagenum)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            db.Orders.Remove(order);
            db.SaveChanges();

            return RedirectToAction("Index", new { pagenum = pagenum });
        }

        //// POST: Order/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Order order = db.Orders.Find(id);
        //    db.Orders.Remove(order);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        public string Result(int clientId, string status, int amount, double endUserPrice)
        {
            logger.Debug("Order Result clientId " + clientId + " status " + status + " amount " + amount + " endUserPrice " + endUserPrice);
            //Order order = db.Orders.Find(IDOrder);
            
            Order order = db.Orders.Find(clientId);

            order.tokens = amount;
            order.price = (float)endUserPrice;
            order.state = (status == "success") ? Order.OrderState.PASS : Order.OrderState.FAIL;
            order.user = order.user;
            
            if (order.state == Order.OrderState.PASS)
            {
                order.user.Tokens += amount;
            }

            db.SaveChanges();

            try
            {
                MailMessage mailMessage = new MailMessage();
                mailMessage.To.Add(order.user.Email);
                mailMessage.From = new MailAddress("support@komudo.com");
                mailMessage.Subject = "Your token order";

                string body = "Dear " + order.user.Name + ", your transaction ";
                if (status == "success")
                {
                    body += "was successful!\n";
                }
                else
                {
                    body += "failed!\n";
                }
                body += "Tokens: " + order.tokens + "\n";
                body += "Price: " + order.price + "\n";
                body += "Cheers,\nKomudo team.";

                mailMessage.Body = body;

                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Send(mailMessage);
                Response.Write("E-mail sent!");
            }
            catch (Exception ex)
            {
                Response.Write("Could not send the e-mail - error: " + ex.Message);
                return ex.Message;
            }

            return "200";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iep-newer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    <script src="/Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src="/Vendor/trianglify/dist/trianglify.min.js"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*<script type="text/javascript" src="http://stage.centili.com/widget/js/c-mobile-payment-scripts.js"></script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Komudo! search", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @if ((System.Web.HttpContext.Current.User != null) && System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Create new auction", "Create", "Auction")</li>

                        }
                        else
                        {
                            @*<li>@Html.ActionLink("Order Tokens", "Create", "Order")</li>*@
                            <li>
                                <a id="c-mobile-payment-widget" href="">
                                    <!--8f05d265beac354447174292aff93074-->
                                 Order Tokens 
                                </a>
                                @*<a id="hidden" href="">nes</a>
                                <a id="c-mobile-payment-widget" href="http://stage.centili.com/widget/WidgetModule?api=2c4e96f8c5eaf1dae401dd4e9e5dd348&clientId=ajde@be.vise&orderId=1">
                                    <!--8f05d265beac354447174292aff93074-->
                                    random
                                </a>
                                <a id="c-mobile-payment-widget2" href="http://stage.centili.com/widget/WidgetModule?api=2c4e96f8c5eaf1dae401dd4e9e5dd348"><img src="https://www.centili.com/images/centili-widget-button.png" /></a>*@
                            </li>
                            <li>@Html.ActionLink("See Previous Orders", "Index", "Order")</li>
                            <li><a><p class="token_count" style="display:inline;">@User.Identity.GetApplicationUser().Tokens</p> <img src="~/Content/Thunder-T.png" width="30px" height="23px" style="float:right; display:inline"></a></li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KoMudo! Auction Engine</p>
        </footer>
    </div>

        
    @*@section scripts
    {
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/jquery.signalR-2.2.1.js")
        @Scripts.Render("~/signalr/hubs")
    }*@
    @RenderSection("scripts", required: false)

    
    <script>
        $(function () {

              // set up the base pattern
              var pattern = Trianglify({
                height: window.innerHeight * 2,
                width: window.innerWidth,
                cell_size: 30 + Math.random() * 100,
                  //x_colors: ['#44036F', '#7E07A9', '#FFFFFF']
                //x_colors: ['#B764D4', '#FFFFFF']
                  //x_colors: ['#B764D4', '#44036F']
                //x_colors: 'Paired'
                  x_colors: 'Greys'
                  //x_colors: 'Purples'
              })

              // canvas
              //document.body.appendChild(pattern.canvas())

              // svg
              //document.body.appendChild(pattern.svg())

              // png
              var png = document.createElement('img')
              png.src = pattern.png()
              //console.log(pattern.png());
              //document.body.appendChild(png)

              document.body.style['background-image'] = 'url(' + pattern.png() + ')';

        });

        $(function () {
            console.log("ready!");
        });

        $(function () {
            console.log("NESTO");
            $('#c-mobile-payment-widget').click(function(e) {
            //$('#hidden').click(function (e) {
                console.log("finished ajax request222! ");
                e.preventDefault();
                e.stopPropagation();
                $.ajax({
                    url: "@Url.Action("New", "Order")",// new { user_name = User.Identity.Name)",
                    success: function (result) {
                        //if (result.isOk == false) alert(result.message);
                        console.log("finished ajax request! ");
                        window.location = "http://stage.centili.com/widget/WidgetModule?api=2c4e96f8c5eaf1dae401dd4e9e5dd348&clientId=" + result;
                        @*$('#c-mobile-payment-widget').attr("href", "http://stage.centili.com/widget/WidgetModule?api=2c4e96f8c5eaf1dae401dd4e9e5dd348&clientId=@User.Identity.Name" + "&orderId=" + result);
                        $('#c-mobile-payment-widget').trigger("click");
                        console.log($('#c-mobile-payment-widget'));
                        console.log($('#c-mobile-payment-widget').attr("href"));*@
                    },
                    async: true
                });
            });
        });
    </script>
</body>


</html>